name: simple-workflow.yml

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 * * * *" 
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: echo "Récupération du code source"
      - name: Check end
        run: echo "Vérification terminée"
