name: simple-workflow.yml

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 * * * *" 
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo "Récupération du code source"
          echo "Vérification terminée"
